### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by s-mag**
Indentation Errors solved

### CODE REVIEW

**Comment by abhijitnathwani** [comment]
@jontymagan I am curious. Was the indentation causing any errors on launch?

**Comment by s-mag** [comment]
> I am curious. Was the indentation causing any errors on launch?

Yes , the code didn't worked in Python 3.7

**Comment by abhijitnathwani** [comment]
For python3, please test with this [branch](https://github.com/abhijitnathwani/PyQuiz/tree/PyQuiz-Python3)

**Comment by abhijitnathwani** [comment]
The code in the master is for Python2.7

**Pull request closed without merging**
